server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lanyue
    username: root
    password: root
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl